version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-v3-{{ checksum "package.json" }}
            - dependency-cache-v3-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-v3-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Linter
          command: yarn lint
      - run:
          name: Run Tests
          command: yarn test --ci --coverage --testResultsProcessor="jest-junit" -i
      - run:
          name: Upload to Codacy
          command: yarn cov
      - run:
          name: Move Tests
          command: |
            mkdir -p ~/junit
            mv ./junit.xml ~/junit
      - store_test_results:
          path: ~/junit

  deploy:
    docker:
      - image: circleci/node:12.6.0
    steps:
      - add-ssh-keys
      - run:
          name: Setup Git
          command: |
            git config --global user.email ${GIT_EMAIL}
            git config --global user.name ${GIT_USERNAME}
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-v3-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-v3
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-v3-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Build
          command: yarn build
      - run:
          name: Zip Dist folder
          command: zip -r /tmp/dist.zip ./dist
      - run:
          name: Release
          command: |
            scripts/release.sh

workflows:
  version: 2

  run-tests:
    jobs:
      - test

  auto-test-build:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - develop
    jobs:
      - test
      - deploy:
          requires:
            - test


notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/25d3ef56c762a262dd33
