version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.7.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Linter
          command: npm run lint
      - run:
          name: Run Tests
          command: npm test -- --ci --coverage --testResultsProcessor="jest-junit"
      - run:
          name: Upload to Codacy
          command: npm run cov
      - run:
          name: Move Tests
          command: |
            mkdir -p ~/junit
            mv ./junit.xml ~/junit
      - store_test_results:
          path: ~/junit

  deploy:
    docker:
      - image: circleci/node:8.7.0
    steps:
      - run:
          name: Setup Git
          command: |
            git config --global user.email ${GIT_EMAIL}
            git config --global user.name ${GIT_USERNAME}
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Build
          command: npm run build
      - run:
          name: Zip Dist folder
          command: zip -r /tmp/dist.zip ./dist
      - run:
          name: Release
          command: npm run release
      - store-artifacts:
          path: /tmp/dist.zip

workflows:
  version: 2

  run-tests:
    jobs:
      - test

  auto-test-build:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - develop
    jobs:
      - test
      - deploy:
          requires:
            - test


notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/25d3ef56c762a262dd33
