version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.7.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-

      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Linter
          command: npm run lint
      - run:
          name: Run Tests
          command: npm test -- --ci --coverage --testResultsProcessor="jest-junit"
      - run:
          name: Upload to Codacy
          command: npm run cov
      - run:
          name: Move Tests
          command: |
            mkdir -p ~/junit
            mv ./junit.xml ~/junit
      - store_test_results:
          path: ~/junit
      - run:
          name: Run Build
          command: npm run build
      -  run:
          name: Move Dist folder
          command: mv ./dist /dist
      - store-artifacts:
          path: /dist
