version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.7.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm test -- --coverage
