name: Continuous Integration

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'
jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 12.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.node }}-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ matrix.node }}-deps-
      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Run Linter
        run: yarn lint
      - name: Run Tests
        run: yarn test --ci --coverage -i
      - name: Send to Code Cov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

