name: Continuous Integration

on:
  push:
    branches:
      - '**'
      - '!master'
  pull_request:
    branches:
      - '**'
jobs:
  tests:
    name: Run Tests (${{ github.event_name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 12.x
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ matrix.node }}-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ matrix.node }}-deps-
      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Run Linter
        uses: ./.github/actions/eslint
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          extensions: ".ts, .tsx, .js, .jsx"
          files: src
      - name: Run Tests
        run: yarn test --ci --coverage -i
      - name: Send to Code Cov
        uses: codecov/codecov-action@v1
        if: github.event_name == 'push'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

