name: Nightly Cron

on:
  schedule:
    - cron: 0 13 * * *

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/github-script@0.3.0
        name: Create Deployment
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            await github.repos.createDeployment({
              ...context.repo,
              ref: context.ref.slice(11),
            });
