name: Nightly Cron

on:
  schedule:
    - cron: 0 13 * * *

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create Deployment
        run: yarn deploy:create
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
