name: No PRs to Master

on:
  pull_request:
    branches:
      - 'master'

jobs:
  fail:
    name: Please make them to develop
    runs-on: ubuntu-latest
    steps:
      - name: No PRs to master, please make them to develop
        run: |
          echo "::error::No PRs should be made against master"
          exit 1

