name: Build Release
on:
  deployment: {}
jobs:
  did-tests-pass:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/skip-deployment
        name: Check Skip Deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/deployment-status
        name: Set Deployment Status Failure
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: failure

  release:
    runs-on: ubuntu-latest
    needs: did-tests-pass
    strategy:
      matrix:
        node: [12.x]
    steps:
      - name: Setup Git
        run: |
          git config --global user.email ${GIT_EMAIL}
          git config --global user.name ${GIT_USERNAME}
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      - uses: actions/checkout@v1
        with:
          ref: develop
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      # - name: Cache Dependencies
        # id: cache-dependencies
        # uses: actions/cache@v1
        # with:
          # path: node_modules
          # key: ${{ matrix.node }}-deps-${{ hashFiles('yarn.lock') }}
          # restore-keys: |
            # ${{ matrix.node }}-deps-
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - uses: ./.github/actions/deployment-status
        name: Set Deployment Status In Progress
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: in_progress
      - name: Run Build
        run: yarn build
      - name: Zip Dist Folder
        run: zip -r /tmp/dist.zip ./dist
      - name: Release
        run: scripts/release.sh
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/deployment-status
        name: Set Deployment Status Success
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: success
      - uses: ./.github/actions/deployment-status
        name: Set Deployment Status Failure
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: failure
