name: Build Release

on:
  deployment: {}


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git
        run: |
          git config --global user.email ${GIT_EMAIL}
          git config --global user.name ${GIT_USERNAME}
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Build
        run: yarn build
      - name: Zip Dist Folder
        run: zip -r /tmp/dist.zip ./dist
      - name: Release
        run: scripts/release.sh
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

