name: Build Release
on:
  deployment: {}
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: actions/checkout@v2
        name: Checkout Flexget
        with:
          ref: develop
          repository: Flexget/flexget
          path: flexget
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Setup Git
        run: |
          git config --global user.email $GIT_EMAIL
          git config --global user.name $GIT_USERNAME
          git fetch --no-tag origin +refs/heads/master:refs/remotes/origin/master
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Set Deployment Status In Progress
        run: yarn deploy:status in_progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Build
        run: yarn build
      - name: Zip Dist Folder
        run: zip -r /tmp/dist.zip ./dist
      - name: Release
        run: scripts/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Deployment Status Success
        run: yarn deploy:status success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Deployment Status Failure
        run: yarn deploy:status failure
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
